LIFE_SMS/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('app_sms.urls')),
    path('admin/', admin.site.urls),
    
]

app_sms/urls.py
from django.urls import path, re_path
from . import views


app_name = 'app_sms'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('enviar_sms/', views.enviar_sms, name='enviar_sms'),
 
]

app_sms/models.py
from django.db import models

# Create your models here.




class Pessoa(models.Model):
    nome = models.CharField(max_length=200)
    genero = models.CharField(max_length=12)
    data_nascimento = models.DateField()
    bi = models.CharField(max_length=20, unique=True)
    residencia = models.CharField(max_length=90, blank=True, null=True)
    telefone = models.CharField(max_length=30, blank=True, null=True, default="--")
    email = models.EmailField(max_length=60, blank=True, null=True, default="sms@gmail.com")
    #municipio = models.ForeignKey(Municipio, on_delete=models.CASCADE, parent_link=True)
    
    def __str__(self):
        return self.id



class Enviar_sms(models.Model):
    telefone = models.CharField(max_length=18, default=" ")
    #email = models.EmailField(max_length=60, blank=True, null=True, default="sms@gmail.com")
    sms = models.CharField(max_length=390, blank=True, null=True)
    
    def __str__(self):
        return self.id

app_sms/forms.py
#
# forms.py
# @Author : Gunza Ismael (7ilipe@gmail.com)
# @Link   : 
# @Date   : 12/09/2019, 00:33:33
from django import forms
from django.forms import ModelForm
from app_sms.models import Enviar_sms, Pessoa



class Mensagem_Form(ModelForm):
    class Meta:
        model = Enviar_sms
        fields = ['telefone', 'sms']
        widgets = {
            'telefone': forms.TextInput(attrs={'class': 'form-control'}),
            #'email': forms.TextInput(attrs={'class': 'form-control'}),
            'sms': forms.Textarea(attrs={'type':'textarea', 'class': 'form-control'}),
        }
    #sms = forms.CharField(required=False, widget=forms.Select(choices = TIPO_DECLARACAO , attrs={'class': 'form-control'}))
    

app_sms/views.py
from django.shortcuts import render
import random, json, re, os, sweetify
from django.core import serializers
from django.urls import reverse
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_protect
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, JsonResponse, HttpRequest, Http404, HttpResponse, FileResponse
from django.core.exceptions import ObjectDoesNotExist
from app_sms.forms import Mensagem_Form
from twilio.rest import Client
import os

# Create your views here.




def home(request):
    context = {}
    return render (request, 'home_centro.html', context)



def enviar_sms(request):
    form = Mensagem_Form(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            account = "AC8158560609ad1dab700b9d33aba03e66"
            token = "05989749d865919e0eccc041a0f7683d"
            client = Client(account, token)
            #+19282966246
            message = client.messages.create(
                to="+244 924 76 26 46", 
                from_="+1 928 296 6246",
                body="seja bem vindo ao salakiaku..!"
                )
            form.save()
            sweetify.success(request, 'Menssagem enviada com sucesso!....', button='Ok', timer='3100')
            return HttpResponseRedirect(reverse('app_sms:home'))

    context = {'form':form}
    return render (request, 'app/enviar_sms.html', context)




#@login_required
"""def sair(request):
    try:
        logout(request)
        #return HttpResponseRedirect(reverse('utilizador:login'))
    except Exception as e:
        raise Http404("erro a terminar a sessão %s " % (e))"""

templates/app/enviar_sms.html
<!DOCTYPE html>{% extends 'home_base.html' %}{% block corpo %}{% load static %}
<!--
@File   : enviar_sms.html
@Author : Gunza Ismael ({__email})
@Link   : 
@Date   : 12/09/2019, 10:55:04
-->
<div class="col-md-12 modal-example">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">

                <h4>Enviar Menssagem</h4>
            </div>
            <div class="panel-body">

                <div class="col-md-12">
                    <div class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title"></h4>
                                </div>

                                <form role="form" action="{% url 'app_sms:enviar_sms' %}" method="POST">
                                    {% csrf_token %} {% autoescape on %}
                                    <div class="modal-body">

                                        <div class="form-group " style="margin: 10px 0px !important;">
                                            <label class="col-sm-10 control-label ">Telefone:</label> {{ form.telefone }} {{ form.telefone.errors }}
                                        </div>
                                        <div class="form-group " style="margin: 10px 0px !important;">
                                            <label class="col-sm-10 control-label ">Mensagem:</label> {{ form.sms }} {{ form.sms.errors }}
                                        </div>

                                    </div>

                                    <div class="modal-footer">
                                        <button type="submit" class="btn btn-primary">ENVIAR </button>
                                    </div>
                                    {% endautoescape %}
                                </form>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                </div>

            </div>
        </div>
    </div>
    {% endblock %}

templates/home_base.html
<!DOCTYPE html>
<!--
@File   : home.html
@Author : Gunza Ismael ({__email})
@Link   :
@Date   : 16/06/2019, 11:58:58
-->
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="description" content="sofil web v.1">
    <meta name="author" content="gunza ismael">
    <meta name="keyword" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>LIFE-SMS</title>

    <!-- start: Css -->
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/bootstrap.min.css' %}">
    <link href="{% static '/asset/css/sweetalert2.css' %}" rel="stylesheet">

    <!-- plugins -->
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/plugins/font-awesome.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/plugins/simple-line-icons.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/plugins/animate.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/plugins/datatables.bootstrap.min.css' %}" />
    <link rel="stylesheet" type="text/css" href="{% static '/asset/css/plugins/fullcalendar.min.css' %}" />
    <link href="{% static '/asset/css/style.css' %}" rel="stylesheet">
    <link href="{% static '/asset/css/estilo.css' %}" rel="stylesheet">
    <!-- end: Css -->

    <link rel="shortcut icon" href="{% static '/asset/img/sms1.jpg' %}">
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body id="mimin" class="dashboard">
    <!-- start: Header -->
    <nav class="navbar navbar-default header navbar-fixed-top">
        <div class="col-md-12 nav-wrapper">
            <div class="navbar-header" style="width:100%;">
                <div class="opener-left-menu is-open">
                    <span class="top"></span>
                    <span class="middle"></span>
                    <span class="bottom"></span>
                </div>
                <a href="{% url 'app_sms:home' %}" class="navbar-brand">
                    <b>+ SMS</b>
                </a>
                <ul class="nav navbar-nav navbar-right user-nav">
                    <li class="user-name"><span> Sofil Web</span></li>
                    <li class="dropdown avatar-dropdown">
                        <img src="{% static '/asset/img/user.png' %}" class="img-circle avatar" alt="user name" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true" />
                        <ul class="dropdown-menu user-dropdown">
                            <li><a href="#"><span class="fa fa-user"></span> Perfil</a></li>
                            <li role="separator" class="divider"></li>
                            <li class="more">
                                <ul>
                                    <li><a href=""><span class="fa fa-cogs"></span></a></li>
                                    <li><a href=""><span class="fa fa-power-off "></span></a></li>
                                </ul>
                            </li>
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <!-- end: Header -->
    <div class="container-fluid mimin-wrapper">
        <!-- start:Left Menu -->
        <div id="left-menu">
            <div class="sub-left-menu scroll">
                <ul class="nav nav-list">
                    <li>
                        <div class="left-bg"></div>
                    </li>
                    <li class="">
                        <div class="col-md-12">
                            <img src="{% static '/asset/img/sms1.jpg' %}" class="col-md-12 img-circle" />
                        </div>
                    </li>

                    <li class="active ripple">
                        <br>
                        <a class="tree-toggle nav-header"><span class="fa-home fa"></span> Serviços
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href=""> Cadastrar Utilizador</a></li>
                            <li><a href="{% url 'app_sms:enviar_sms' %}"> Enviar Menssagem</a></li>

                        </ul>
                    </li>

                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-diamond fa"></span> Finanças
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li><a href="">Registar Pagamento</a></li>
                            <li><a href="">Listar Pagamento</a></li>
                            <li><a href="">Listar Divida</a></li>
                        </ul>
                    </li>

                    <li class="ripple">
                        <a class="tree-toggle nav-header">
                            <span class="fa-area-chart fa"></span> Estatística
                            <span class="fa-angle-right fa right-arrow text-right"></span>
                        </a>
                        <ul class="nav nav-list tree">
                            <li class="ripple">
                                <a class="sub-tree-toggle nav-header">
                                    <span class="fa fa-bar-chart-o"></span> Categoria
                                    <span class="fa-angle-right fa right-arrow text-right"></span>
                                </a>
                                <ul class="nav nav-list sub-tree">
                                    <li><a href="">Por Especialidade</a></li>
                                    <li><a href="">Por Curso</a></li>
                                    <li><a href="">Por Semestre</a></li>
                                </ul>
                            </li>

                        </ul>
                    </li>

                </ul>
            </div>
        </div>
        <!-- end: Left Menu -->


        <!-- start: content -->
        <div id="content">
            <div class="panel box-shadow-none content-header">
                <div class="panel-body">
                    <div class="col-md-12">
                        <h3 class="animated fadeInLeft"> <strong> SERVIÇOS DE MENSAGEM</strong> </h3>

                    </div>
                </div>
            </div>

            {% block corpo %} kfjkd {% endblock %}
            <div class="col-md-12">
                <div class="panel bg-green text-white">

                </div>
            </div>
        </div>
    </div>
    <!-- end: content -->

    </div>

    <button id="mimin-mobile-menu-opener" class="animated rubberBand btn btn-circle btn-danger">
        <span class="fa fa-bars"></span>
    </button>
    <!-- end: Mobile -->

    <!-- start: Javascript -->
    <script src="{% static '/asset/js/jquery.min.js' %}"></script>
    <script src="{% static '/asset/js/jquery.ui.min.js' %}"></script>
    <script src="{% static '/asset/js/bootstrap.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/jquery.nicescroll.js' %}"></script>


    <!-- plugins -->
    <script src="{% static '/asset/js/plugins/moment.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/jquery.datatables.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/datatables.bootstrap.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/fullcalendar.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/jquery.vmap.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/maps/jquery.vmap.world.js' %}"></script>
    <script src="{% static '/asset/js/plugins/jquery.vmap.sampledata.js' %}"></script>
    <script src="{% static '/asset/js/plugins/jquery.mask.min.js' %}"></script>
    <script src="{% static '/asset/js/plugins/chart.min.js' %}"></script>
    <script src="{% static '/asset/js/wizard.js' %}"></script>
    <script src="{% static '/asset/js/sweetalert2.js' %}"></script>
    </script>


    <!-- custom -->
    <script src="{% static '/asset/js/main.js' %}"></script>
    <script type="text/javascript">
        $(document).ready(function() {
            $('#datatables-example').DataTable();

        });
    </script>
    {% load sweetify %} {% sweetify %}


</body>

</html>

templates/home_centro.html
{% extends 'home_base.html' %}{% block corpo %}{% load static %}


<!-- start: Content -->

<div class="col-md-12 modal-example">
    <div class="panel">
        <div class="col-md-3">

        </div>
        <div class="col-md-9">
            <div class="modal-body">
                <img src="{% static '/asset/img/sms1.jpg' %}" class="col-md-7  col-sm-12 img-circle" />
            </div>
        </div>

        <div class="col-md-2">

        </div>
    </div>

</div>
<!-- end: Content -->


{% endblock %}

templates/secretaria/consultar_e_declaracao.html
<!DOCTYPE html> {% extends 'home_base.html' %}{% block corpo %}{% load static %}
<!--
@File   : emitir_declaracao.html
@Author : Gunza Ismael ({__email})
@Link   : 
@Date   : 17/07/2019, 00:00:44
-->

<div class="col-md-12 modal-example">
    <div class="col-md-12">
        <div class="panel">
            <div class="panel-heading">
                {% if escolha == 2 %}
                <h4>Consultar Dados do Estudante </h4>
                {% else %}
                <h4>Emitir Declaração do Estudante</h4>
                {% endif %}
            </div>
            <div class="panel-body">

                <div class="col-md-12">
                    <div class="modal fade">
                        <div class="modal-dialog">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h4 class="modal-title"></h4>
                                </div>
                                {% if escolha == 2 %}
                                <form role="form" action="{% url 'secretaria:consultar-dados-pessoal' %}" method="POST">
                                    {% else %}
                                    <form role="form" action="{% url 'secretaria:emitir-delaracao' %}" method="POST" target="_blank">
                                        {% endif %} {% csrf_token %} {% autoescape on %}
                                        <div class="modal-body">

                                            <div class="form-group " style="margin: 10px 0px !important;">
                                                <label class="col-sm-10 control-label ">Nº Estudante / Nº BI</label> {{ form.bi }} {{ form.bi.errors }}
                                            </div>
                                            <div class="form-group " style="margin: 10px 0px !important;">
                                                <label class="col-sm-10 control-label ">Grau</label> {{ form.grau }} {{ form.grau.errors }}
                                            </div>
                                            {% if escolha != 2 %}
                                            <div class="form-group " style="margin: 10px 0px !important;">
                                                <label class="col-sm-10 control-label ">Opção</label> {{ form.tipo }} {{ form.tipo.errors }}
                                            </div>
                                            {% else %}
                                            <div class="form-group " style="margin: 10px 0px !important;">
                                                <label class="col-sm-10 control-label ">Opção de Consulta</label> {{ form.tipo_consulta }} {{ form.tipo_consulta.errors }}
                                            </div>
                                            {% endif %}
                                        </div>
                                        {% if escolha == 2 %}
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">CONSULTAR</button>
                                        </div>
                                        {% else %}
                                        <div class="modal-footer">
                                            <button type="submit" class="btn btn-primary">EMITIR </button>
                                        </div>
                                        {% endif %} {% endautoescape %}
                                    </form>
                            </div>
                            <!-- /.modal-content -->
                        </div>
                        <!-- /.modal-dialog -->
                    </div>
                    <!-- /.modal -->
                </div>

            </div>
        </div>
    </div>
    {% endblock %}